In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as skl
%matplotlib inline

In [87]:
import numpy as np

In [28]:
data = pd.read_csv("C:/Users/HP/Documents/data science competitions/american express analyze this 2017/Training_Dataset.csv")

In [50]:
baseline_data.head(5)

mvar2   mvar3  mvar4  mvar5  mvar6   mvar7   mvar8    mvar9  mvar10  \
0      0  106920      4     18    970  0.7969  0.1831   337236       1   
1      2       0      4     19   1030  0.0678  0.0000  2918974       1   
2      2  399168      4     35    327  0.7551  0.2986   498656       0   
3      0  267300      4    274   1258  0.7969  0.5297  2480074       1   
4      0  213840      6      1      0  2.3238  0.0000  2918974       0   

   mvar11    ...      mvar40  mvar41  mvar42  mvar43  mvar44  mvar45  mvar46  \
0  6.0899    ...           0       0       0       0       0       0       0   
1  4.2016    ...           0       0       0       0       0       0       1   
2  3.3760    ...           0       0       0       0       0       0       0   
3  4.1082    ...           1       0       0       1       0       0       0   
4  0.0000    ...           0       0       0       0       0       0       1   

   mvar47  mvar48  card_type  
0       0       1          0  
1       0       0          0  
2       0       1          0  
3       0       1          2  
4       0       0          0  

[5 rows x 47 columns]

In [108]:
baseline_data = data.drop(['cm_key','mvar1','mvar12'],axis=1)

In [109]:
baseline_data['card_type'] = 0

In [110]:
baseline_data['card_type'].loc[baseline_data['mvar49']==1] = 3

C:\Users\HP\Anaconda3\lib\site-packages\pandas\core\indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [111]:
baseline_data['card_type'].loc[baseline_data['mvar50']==1] = 1

C:\Users\HP\Anaconda3\lib\site-packages\pandas\core\indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [112]:
baseline_data['card_type'].loc[baseline_data['mvar51']==1] = 2

C:\Users\HP\Anaconda3\lib\site-packages\pandas\core\indexing.py:179: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [113]:
baseline_data.drop(['mvar49','mvar50','mvar51'],axis=1,inplace=True)

In [114]:
baseline_data.drop(['mvar46','mvar47','mvar48'],axis=1,inplace=True)

In [53]:
from sklearn.ensemble import GradientBoostingClassifier

In [35]:
from sklearn.cross_validation import train_test_split

In [115]:
baseline_data_y = baseline_data.card_type
baseline_data_x = baseline_data.drop('card_type',axis=1)

In [116]:
x_train,x_test,y_train,y_test = train_test_split(baseline_data_x,baseline_data_y,train_size=0.7)

In [77]:
gb = GradientBoostingClassifier(n_estimators=1000,learning_rate=0.1)

In [117]:
gb.fit(x_train,y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
              learning_rate=0.1, loss='deviance', max_depth=3,
              max_features=None, max_leaf_nodes=None,
              min_impurity_split=1e-07, min_samples_leaf=1,
              min_samples_split=2, min_weight_fraction_leaf=0.0,
              n_estimators=1000, presort='auto', random_state=None,
              subsample=1.0, verbose=0, warm_start=False)

In [118]:
baseline_prediction = gb.predict(x_test)

In [119]:
baseline_prediction = pd.Series(baseline_prediction)

In [120]:
baseline_prediction.value_counts()

0    11581
3      174
2      138
1      107
dtype: int64

In [121]:
y_test.value_counts()

0    9351
3    1000
2     849
1     800
Name: card_type, dtype: int64

In [407]:
from sklearn.metrics import confusion_matrix

In [408]:
cnf_matrix = confusion_matrix(y_test,baseline_prediction)

In [409]:
cnf_matrix

array([[9115,   50,   73,  113],
       [ 747,   45,    6,    2],
       [ 787,    9,   50,    3],
       [ 932,    3,    9,   56]])

# Random forest classifier

In [252]:
from sklearn.ensemble import RandomForestClassifier

In [371]:
rf = RandomForestClassifier(n_estimators=4,max_depth=100)

In [372]:
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=100, max_features='auto', max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            n_estimators=4, n_jobs=1, oob_score=False, random_state=None,
            verbose=0, warm_start=False)

In [373]:
rf_prediction = rf.predict(x_test)

In [374]:
np.unique(rf_prediction,return_counts=True)

(array([0, 1, 2, 3], dtype=int64),
 array([11245,   254,   203,   298], dtype=int64))

In [313]:
y_test.value_counts()

0    9351
3    1000
2     849
1     800
Name: card_type, dtype: int64

# modifications in leader board data as per training set format


In [70]:
lb_data = pd.read_csv("C:/Users/HP/Documents/data science competitions/american express analyze this 2017/Leaderboard_Dataset.csv")

In [71]:
lb_data.head()

cm_key         mvar1  mvar2  mvar3  mvar4  mvar5  mvar6   mvar7   mvar8  \
0   50001  Charge            2      0      4     18    460  0.2495  0.2310   
1   50002  Charge            2      0      0     45    381  1.9329  0.7196   
2   50003  Charge            0      0      4      3      0  0.7969  0.0000   
3   50004  Charge            1  18711      9     89    432  0.1016  0.5074   
4   50005  Charge            0  21384      4      7      0  0.7969  0.2310   

      mvar9   ...       mvar36     mvar37     mvar38     mvar39  mvar40  \
0    180512   ...     32886.89   11345.47    7914.21    7704.62       0   
1  11295211   ...    104722.52  255544.59  116216.40  152673.00       1   
2     45161   ...     19689.03       0.00       0.00       0.00       0   
3    420972   ...     13154.43    7671.62    3357.24    2651.22       0   
4    880618   ...     32071.78   15376.01   14390.97       0.00       0   

   mvar41  mvar42  mvar43  mvar44  mvar45  
0       0       0       0       0       0  
1       0       0       0       0       0  
2       0       0       0       0       0  
3       1       0       0       0       0  
4       0       0       0       0       0  

[5 rows x 46 columns]

In [72]:
baseline_lb = lb_data.drop(['cm_key','mvar1','mvar12'],axis=1)

In [208]:
baseline_lb_prediction = gb.predict(baseline_lb)

In [210]:
baseline_lb_prediction = pd.DataFrame(data={'cm_key':lb_data.cm_key,'card_type':baseline_lb_prediction})

In [213]:
baseline_lb_prediction.sort_values(by='card_type',ascending=False,inplace=True)

In [215]:
baseline_lb_prediction['predicted_card'] = baseline_lb_prediction.card_type.map({3:'Supp',2:'Credit',1:'Elite',0:'Supp'})

In [235]:
submission = baseline_lb_prediction[['cm_key','predicted_card']][0:1000]

In [239]:
submission.to_csv("C:/Users/HP/Documents/data science competitions/american express analyze this 2017/baseline_submission.csv",index=False,header=False)

### random forest classifier


In [375]:
baseline_rf_prediction = rf.predict(baseline_lb)

In [376]:
baseline_rf_prediction = pd.DataFrame(data={'cm_key':lb_data.cm_key,'card_type':baseline_rf_prediction})

In [377]:
baseline_rf_prediction.sort_values(by='card_type',ascending=False,inplace=True)

In [379]:
baseline_rf_prediction.predicted_card.value_counts()

Supp      9588
Elite      207
Credit     205
Name: predicted_card, dtype: int64

In [378]:
baseline_rf_prediction['predicted_card'] = baseline_rf_prediction.card_type.map({3:'Supp',2:'Credit',1:'Elite',0:'Supp'})

In [380]:
submission_rf = baseline_rf_prediction[['cm_key','predicted_card']][0:1000]

In [382]:
submission_rf.to_csv("C:/Users/HP/Documents/data science competitions/american express analyze this 2017/baseline_submission_rf.csv",index=False,header=False)

In [381]:
submission_rf.predicted_card.value_counts()


Supp      588
Elite     207
Credit    205
Name: predicted_card, dtype: int64

### xgb

In [387]:
import xgboost as xgb

In [388]:
from xgboost.sklearn import XGBClassifier

In [404]:
xgb1 = XGBClassifier(max_depth=100,n_estimators=100)

In [405]:
xgb1.fit(x_train,y_train)

XGBClassifier(base_score=0.5, colsample_bylevel=1, colsample_bytree=1,
       gamma=0, learning_rate=0.1, max_delta_step=0, max_depth=100,
       min_child_weight=1, missing=None, n_estimators=100, nthread=-1,
       objective='multi:softprob', reg_alpha=0, reg_lambda=1,
       scale_pos_weight=1, seed=0, silent=True, subsample=1)

In [410]:
xgb_pred = xgb1.predict(x_test)

In [393]:
y_test.value_counts()

0    9351
3    1000
2     849
1     800
Name: card_type, dtype: int64

In [411]:
confusion_matrix(y_test,xgb_pred)

array([[9262,   23,   23,   43],
       [ 761,   30,    8,    1],
       [ 812,    6,   30,    1],
       [ 953,    5,    6,   36]])

### logistic regression

In [412]:
from sklearn.linear_model import LogisticRegression

In [413]:
lr = LogisticRegression()

In [414]:
lr.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [415]:
lr_pred = lr.predict(x_test)

In [416]:
confusion_matrix(y_test,lr_pred)

array([[9310,    2,   22,   17],
       [ 797,    0,    2,    1],
       [ 841,    0,    4,    4],
       [ 987,    1,    8,    4]])

### qda

In [417]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

In [418]:
qda = QuadraticDiscriminantAnalysis()

In [419]:
qda.fit(x_train,y_train)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:695: UserWarning: Variables are collinear
  warnings.warn("Variables are collinear")


QuadraticDiscriminantAnalysis(priors=None, reg_param=0.0,
               store_covariances=False, tol=0.0001)

In [420]:
qda_pred = qda.predict(x_test)

In [421]:
confusion_matrix(y_test,qda_pred)

array([[ 676,  605, 7593,  477],
       [  23,  118,  640,   19],
       [  50,   34,  749,   16],
       [ 126,   45,  657,  172]])

### lda

In [422]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [423]:
lda = LinearDiscriminantAnalysis()

In [424]:
lda.fit(x_train,y_train)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\discriminant_analysis.py:387: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


LinearDiscriminantAnalysis(n_components=None, priors=None, shrinkage=None,
              solver='svd', store_covariance=False, tol=0.0001)

In [426]:
lda_pred = lda.predict(x_test)

In [427]:
confusion_matrix(y_test,lda_pred)

array([[9152,   31,    9,  159],
       [ 764,   32,    1,    3],
       [ 837,   10,    0,    2],
       [ 882,    5,    5,  108]])

In [428]:
lda_lb_prediction = lda.predict(baseline_lb)

In [429]:
baseline_lda_prediction = pd.DataFrame(data={'cm_key':lb_data.cm_key,'card_type':lda_lb_prediction})

In [430]:
baseline_lda_prediction.sort_values(by='card_type',ascending=False,inplace=True)

In [432]:
baseline_lda_prediction['predicted_card'] = baseline_lda_prediction.card_type.map({3:'Supp',2:'Credit',1:'Elite',0:'Supp'})

In [433]:
baseline_lda_prediction.predicted_card.value_counts()

Supp      9905
Elite       90
Credit       5
Name: predicted_card, dtype: int64

In [434]:
submission_lda = baseline_lda_prediction[['cm_key','predicted_card']][0:1000]

In [435]:
submission_lda.to_csv("C:/Users/HP/Documents/data science competitions/american express analyze this 2017/baseline_submission_lda.csv",index=False,header=False)

### SVM WITH FEWER NUMBER OF DATA POINTS

In [437]:
baseline_data.card_type.value_counts()


0    31122
3     3447
2     2777
1     2654
Name: card_type, dtype: int64

In [438]:
balanced_df = baseline_data.drop(baseline_data[baseline_data['card_type']==0].sample(frac=0.8).index)

In [439]:
balanced_df.card_type.value_counts()

0    6224
3    3447
2    2777
1    2654
Name: card_type, dtype: int64

In [440]:
from sklearn.svm import SVC

In [441]:
vector_machine = SVC()

In [442]:
x_balanced = balanced_df.drop('card_type',axis=1)
y_balanced = balanced_df['card_type']

In [455]:
vector_machine.fit(x_train,y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape=None, degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [456]:
svm_pred = vector_machine.predict(baseline_lb)

In [457]:
baseline_svm_prediction = pd.DataFrame(data={'cm_key':lb_data.cm_key,'card_type':svm_pred})

In [458]:
baseline_svm_prediction.sort_values(by='card_type',ascending=False,inplace=True)

In [459]:
baseline_svm_prediction['predicted_card'] = baseline_svm_prediction.card_type.map({3:'Supp',2:'Credit',1:'Elite',0:'Supp'})

In [464]:
baseline_svm_prediction.card_type.value_counts()

0    10000
Name: card_type, dtype: int64

In [461]:
submission_svm = baseline_svm_prediction[['cm_key','predicted_card']][0:1000]

In [462]:
submission_svm.to_csv("C:/Users/HP/Documents/data science competitions/american express analyze this 2017/baseline_submission_svm.csv",index=False,header=False)